### ISSUE TITLE
how i get the updated 2019 hierarchy file?

### ISSUE THREAD

**Issue by mateusrangel** [cortext/patstat#11]

**Comment by gnupablo** [comment]
Hello Mateus,

Currently we don't have option to build the hierarchy for 2019, but we have built the last hierarchy available from the API that we are rely on, so you can download the virtual machine using this [link](http://tiny.cc/c11h8y) and you can following our tutorial [here](https://github.com/cortext/patstat/tree/feature/ipc_patstat_2017/nomenclatures/ipc_descriptions), in order to get the IPC codes.
